### ISSUE TITLE
Speakers - Add sessionize speakers

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.com#150]
Add as a clickthrough link until the following embeds are styled.
<script type="text/javascript" src="https://sessionize.com/api/v2/c6srvgg4/view/SpeakerWall"></script>
<script type="text/javascript" src="https://sessionize.com/api/v2/c6srvgg4/view/Speakers"></script>

**Comment by Divyansh-0** [comment]
Can you clarify where you need the link??
