### ISSUE TITLE
Make site responsive

### ISSUE THREAD

**Issue by sambonuruddeen** [datafestafrica/datafestafrica.com#50]
The Nav Banner  and Logo are not compatible with mobile devices

**Comment by goodtocode** [comment]
Hi @sambonuruddeen, mind taking another look after the recent changes? If you see issues, can you please list them here and we'll start correcting the remaining responsive problems? Thanks for noticing the responsive issues!

**Comment by sambonuruddeen** [comment]
I will take a look and give you an update during the weekend @goodtocode
